[package]
name = "elementary_cellular_automata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.6"
maplit = "1.0.2"
rand = "0.8.5"
